# Generated by Django 3.0.6 on 2020-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatory',
            name='verification_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='signatory',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
