# Generated by Django 3.0.6 on 2020-05-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatories', '0002_auto_20200509_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signatory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='signatory',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
