# Generated by Django 3.0.6 on 2020-05-15 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signatories', '0003_auto_20200512_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signatory',
            options={'verbose_name_plural': 'Signatories'},
        ),
    ]
