name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coveralls pyflakes
        pip freeze
        echo "from .dev import *" > nfvnr/settings/__init__.py
    - name: Check formatting
      run: |
        ./pyflakes.sh
    - name: Run tests
      run: |
        coverage run --source=signatories manage.py test
    - name: Submit coverage results
      run: |
        coveralls
